spring:
  application:
    name: user-service
  data:
    mongodb:
      database: user-service
      host: localhost
      port: 27017
      password: bdung
      username: mongoadmin

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.5
