spring:
  application:
    name: survey-service
  data:
    mongodb:
      host: localhost
      port: 27017
      password: bdung
      username: mongoadmin
      authentication-database: admin
springdoc:
  swagger-ui:
    path: /swagger-ui.html
