spring:
  application:
    name: survey-service
  data:
    mongodb:
      host: rc1a-iaj8kf6jaomgk9lf.mdb.yandexcloud.net
      port: 27018
      password: goeasysurvey
      username: survey-service
      database: survey-service
      authentication-database: survey-service
springdoc:
  swagger-ui:
    path: /swagger-ui.html
