server:
  port: 8083

spring:
  application:
    name: survey-service
  data:
    mongodb:
      database: survey-service
      host: localhost
      port: 27017
      password: bdung
      username: mongoadmin
springdoc:
  swagger-ui:
    path: /swagger-ui.html
de:
  flapdoodle:
    mongodb:

      embedded:
        version: 6.0.5

